"""
    Dissertation Service

    A set of API endpoints that allow you to get information about dissertation  # noqa: E501

    The version of the OpenAPI document: 1.00
    Generated by: https://openapi-generator.tech
"""


import unittest

import osis_dissertation_sdk
from osis_dissertation_sdk.api.dissertation_api import DissertationApi  # noqa: E501


class TestDissertationApi(unittest.TestCase):
    """DissertationApi unit test stubs"""

    def setUp(self):
        self.api = DissertationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_dissertation_addjurymember(self):
        """Test case for dissertation_addjurymember

        """
        pass

    def test_dissertation_back_to_draft(self):
        """Test case for dissertation_back_to_draft

        """
        pass

    def test_dissertation_can_edit_dissertation(self):
        """Test case for dissertation_can_edit_dissertation

        """
        pass

    def test_dissertation_can_manage_jury_member(self):
        """Test case for dissertation_can_manage_jury_member

        """
        pass

    def test_dissertation_create(self):
        """Test case for dissertation_create

        """
        pass

    def test_dissertation_deactivate(self):
        """Test case for dissertation_deactivate

        """
        pass

    def test_dissertation_deletejurymember(self):
        """Test case for dissertation_deletejurymember

        """
        pass

    def test_dissertation_detail(self):
        """Test case for dissertation_detail

        """
        pass

    def test_dissertation_history(self):
        """Test case for dissertation_history

        """
        pass

    def test_dissertation_list(self):
        """Test case for dissertation_list

        """
        pass

    def test_dissertation_submit(self):
        """Test case for dissertation_submit

        """
        pass

    def test_dissertation_update(self):
        """Test case for dissertation_update

        """
        pass

    def test_retrieve_dissertation_file(self):
        """Test case for retrieve_dissertation_file

        """
        pass

    def test_update_dissertation_file(self):
        """Test case for update_dissertation_file

        """
        pass


if __name__ == '__main__':
    unittest.main()
