"""
    Dissertation Service

    A set of API endpoints that allow you to get information about dissertation  # noqa: E501

    The version of the OpenAPI document: 1.00
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_dissertation_sdk
from osis_dissertation_sdk.model.proposition_dissertation_author import PropositionDissertationAuthor
from osis_dissertation_sdk.model.proposition_dissertation_jury import PropositionDissertationJury
from osis_dissertation_sdk.model.proposition_dissertation_link import PropositionDissertationLink
globals()['PropositionDissertationAuthor'] = PropositionDissertationAuthor
globals()['PropositionDissertationJury'] = PropositionDissertationJury
globals()['PropositionDissertationLink'] = PropositionDissertationLink
from osis_dissertation_sdk.model.proposition_dissertation_detail import PropositionDissertationDetail


class TestPropositionDissertationDetail(unittest.TestCase):
    """PropositionDissertationDetail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPropositionDissertationDetail(self):
        """Test PropositionDissertationDetail"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PropositionDissertationDetail()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
