"""
    Dissertation Service

    A set of API endpoints that allow you to get information about dissertation  # noqa: E501

    The version of the OpenAPI document: 1.00
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_dissertation_sdk
from osis_dissertation_sdk.model.proposition_dissertation_author import PropositionDissertationAuthor


class TestPropositionDissertationAuthor(unittest.TestCase):
    """PropositionDissertationAuthor unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPropositionDissertationAuthor(self):
        """Test PropositionDissertationAuthor"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PropositionDissertationAuthor()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
