"""
    Dissertation Service

    A set of API endpoints that allow you to get information about dissertation  # noqa: E501

    The version of the OpenAPI document: 1.00
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_dissertation_sdk
from osis_dissertation_sdk.model.proposition_dissertation_row import PropositionDissertationRow


class TestPropositionDissertationRow(unittest.TestCase):
    """PropositionDissertationRow unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPropositionDissertationRow(self):
        """Test PropositionDissertationRow"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PropositionDissertationRow()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
