"""
    Dissertation Service

    A set of API endpoints that allow you to get information about dissertation  # noqa: E501

    The version of the OpenAPI document: 1.00
    Generated by: https://openapi-generator.tech
"""


import unittest

import osis_dissertation_sdk
from osis_dissertation_sdk.api.proposition_dissertation_api import PropositionDissertationApi  # noqa: E501


class TestPropositionDissertationApi(unittest.TestCase):
    """PropositionDissertationApi unit test stubs"""

    def setUp(self):
        self.api = PropositionDissertationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_proposition_detail(self):
        """Test case for proposition_detail

        """
        pass

    def test_propositions_list(self):
        """Test case for propositions_list

        """
        pass

    def test_retrieve_proposition_dissertation_file(self):
        """Test case for retrieve_proposition_dissertation_file

        """
        pass

    def test_update_proposition_dissertation_file(self):
        """Test case for update_proposition_dissertation_file

        """
        pass


if __name__ == '__main__':
    unittest.main()
