"""
    Dissertation Service

    A set of API endpoints that allow you to get information about dissertation  # noqa: E501

    The version of the OpenAPI document: 1.00
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_dissertation_sdk
from osis_dissertation_sdk.model.dissertation_link import DissertationLink


class TestDissertationLink(unittest.TestCase):
    """DissertationLink unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDissertationLink(self):
        """Test DissertationLink"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DissertationLink()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
