"""
    Dissertation Service

    A set of API endpoints that allow you to get information about dissertation  # noqa: E501

    The version of the OpenAPI document: 1.01
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_dissertation_sdk
from osis_dissertation_sdk.model.dissertation_submit_command import DissertationSubmitCommand


class TestDissertationSubmitCommand(unittest.TestCase):
    """DissertationSubmitCommand unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDissertationSubmitCommand(self):
        """Test DissertationSubmitCommand"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DissertationSubmitCommand()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
