"""
    Dissertation Service

    A set of API endpoints that allow you to get information about dissertation  # noqa: E501

    The version of the OpenAPI document: 1.01
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_dissertation_sdk
from osis_dissertation_sdk.model.defend_period_enum import DefendPeriodEnum
globals()['DefendPeriodEnum'] = DefendPeriodEnum
from osis_dissertation_sdk.model.dissertation_create_command import DissertationCreateCommand


class TestDissertationCreateCommand(unittest.TestCase):
    """DissertationCreateCommand unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDissertationCreateCommand(self):
        """Test DissertationCreateCommand"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DissertationCreateCommand()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
