# flake8: noqa

# import all models into this package
# if you have many models here with many references from one model to another this may
# raise a RecursionError
# to avoid this, import only the models that you directly need like:
# from from osis_dissertation_sdk.model.pet import Pet
# or import this package, but before doing it, use:
# import sys
# sys.setrecursionlimit(n)

from osis_dissertation_sdk.model.accepted_language_enum import AcceptedLanguageEnum
from osis_dissertation_sdk.model.adviser import Adviser
from osis_dissertation_sdk.model.adviser_list import AdviserList
from osis_dissertation_sdk.model.defend_period_enum import DefendPeriodEnum
from osis_dissertation_sdk.model.dissertation_author import DissertationAuthor
from osis_dissertation_sdk.model.dissertation_back_to_draft_command import DissertationBackToDraftCommand
from osis_dissertation_sdk.model.dissertation_can_edit_dissertation import DissertationCanEditDissertation
from osis_dissertation_sdk.model.dissertation_can_manage_jury import DissertationCanManageJury
from osis_dissertation_sdk.model.dissertation_create_command import DissertationCreateCommand
from osis_dissertation_sdk.model.dissertation_created_response import DissertationCreatedResponse
from osis_dissertation_sdk.model.dissertation_detail import DissertationDetail
from osis_dissertation_sdk.model.dissertation_file import DissertationFile
from osis_dissertation_sdk.model.dissertation_history_paginated_list import DissertationHistoryPaginatedList
from osis_dissertation_sdk.model.dissertation_history_row import DissertationHistoryRow
from osis_dissertation_sdk.model.dissertation_jury import DissertationJury
from osis_dissertation_sdk.model.dissertation_jury_add_command import DissertationJuryAddCommand
from osis_dissertation_sdk.model.dissertation_jury_added_response import DissertationJuryAddedResponse
from osis_dissertation_sdk.model.dissertation_link import DissertationLink
from osis_dissertation_sdk.model.dissertation_location import DissertationLocation
from osis_dissertation_sdk.model.dissertation_location_list import DissertationLocationList
from osis_dissertation_sdk.model.dissertation_paginated_list import DissertationPaginatedList
from osis_dissertation_sdk.model.dissertation_role_status_enum import DissertationRoleStatusEnum
from osis_dissertation_sdk.model.dissertation_row import DissertationRow
from osis_dissertation_sdk.model.dissertation_status_enum import DissertationStatusEnum
from osis_dissertation_sdk.model.dissertation_submit_command import DissertationSubmitCommand
from osis_dissertation_sdk.model.dissertation_update_command import DissertationUpdateCommand
from osis_dissertation_sdk.model.error import Error
from osis_dissertation_sdk.model.proposition_dissertation_author import PropositionDissertationAuthor
from osis_dissertation_sdk.model.proposition_dissertation_collaboration_enum import PropositionDissertationCollaborationEnum
from osis_dissertation_sdk.model.proposition_dissertation_detail import PropositionDissertationDetail
from osis_dissertation_sdk.model.proposition_dissertation_file import PropositionDissertationFile
from osis_dissertation_sdk.model.proposition_dissertation_jury import PropositionDissertationJury
from osis_dissertation_sdk.model.proposition_dissertation_level_enum import PropositionDissertationLevelEnum
from osis_dissertation_sdk.model.proposition_dissertation_link import PropositionDissertationLink
from osis_dissertation_sdk.model.proposition_dissertation_paginated_list import PropositionDissertationPaginatedList
from osis_dissertation_sdk.model.proposition_dissertation_row import PropositionDissertationRow
from osis_dissertation_sdk.model.proposition_dissertation_type_enum import PropositionDissertationTypeEnum
