# flake8: noqa

"""
    Dissertation Service

    A set of API endpoints that allow you to get information about dissertation  # noqa: E501

    The version of the OpenAPI document: 1.01
    Generated by: https://openapi-generator.tech
"""


__version__ = "1.01"

# import ApiClient
from osis_dissertation_sdk.api_client import ApiClient

# import Configuration
from osis_dissertation_sdk.configuration import Configuration

# import exceptions
from osis_dissertation_sdk.exceptions import OpenApiException
from osis_dissertation_sdk.exceptions import ApiAttributeError
from osis_dissertation_sdk.exceptions import ApiTypeError
from osis_dissertation_sdk.exceptions import ApiValueError
from osis_dissertation_sdk.exceptions import ApiKeyError
from osis_dissertation_sdk.exceptions import ApiException
